HEX

\ FILE CHE SERVE PER INIZIALIZZARE LE COSTANTI CHE VERRANNO UTILIZZATE E CHE DIPENDONO DALLE CONFIGURAZIONI HARDWARE 
\ SPECIFICHE E ALCUNE WORD DI UTILITA'




\ UNICI VALORI DA CAMBIARE PER TUTTO IL PROGRAMMA CHE DIPENDONO DALLA CONFIGURAZIONE DEI PIN E DELL'HARDWARE UTILIZZATO
\ UNICO VINCOLO FRAMEBUFFER 1024x768
\ HO INSERITO DEGLI SPAZI PER DIFFERENZIARE DAL RESTO

3F000000 CONSTANT BASEADDRESS

\ VALORE DI INIZIO DEL FRAMEBUFFER 1024x768
1E8FA000 CONSTANT FRAMEBUFFER

\ INDIRIZZO IN MEMORIA DOVE COMINCIA IL FILE BINARIO CARICATO E I SINGOLI ELEMENTI 
00200000 CONSTANT STARTBG  				\ BACKGROUND 
STARTBG 2FFD00 + CONSTANT STARTFONT		\ FONT
STARTFONT 400 +  CONSTANT STARTOPEN     \ IMMAGINE CASSAFORTE APERTA

\ QUANDO SI SCRIVE IL VALORE NELLE COSTANTI DEI PIN VA IN HEX
1B CONSTANT REDLED		\ PIN 27
17 CONSTANT GREENLED    \ PIN 23

15 CONSTANT MID    \ PIN 21
13 CONSTANT UP     \ PIN 19 
D CONSTANT DOWN    \ PIN 13
16 CONSTANT LEFT   \ PIN 22
11 CONSTANT RIGHT  \ PIN 17 







\ GPIO ALTERNATE FUNCTION SELECT REGISTER 0
BASEADDRESS 200000 + CONSTANT GPFSEL0

\ GPIO OUTPUT SET\CLEAR REGISTERS 0
GPFSEL0 1C + CONSTANT GPSET0
GPFSEL0 28 + CONSTANT GPCLR0

\ GPIO EVENT DETECT STATUS AND FALLING EDGE REGISTERS
GPFSEL0 40 + CONSTANT GPEDS0
GPFSEL0 58 + CONSTANT GPFEN0

\ COLORI PIXEL
00FF0000 CONSTANT RED
0000FF00 CONSTANT GREEN
00000000 CONSTANT BLACK
00FFFFFF CONSTANT WHITE
00FBFBFB CONSTANT LIGHTGREY
00FFFCC0 CONSTANT LIGHTYELLOW
00FFA55F CONSTANT ORANGE

\ SYSTEM TIMER
BASEADDRESS 3004 + CONSTANT SYSTCLO

\ Con 4 elementi la base dello stack in cima
: BASEONTOP   ROT ROT 2SWAP SWAP ;  

\ Calcola il tempo passato, in microsecondi, tra due diverse letture del registro SYSTCLO.
: TIMEPASSED SWAP - ;

\ Loop fino a quando non è passato più tempo di quello specificato in microsecondi.
\ TEMPO (secondi) DELAY
: DELAY   F4240 * SYSTCLO @ BEGIN 2DUP SYSTCLO @ TIMEPASSED <= UNTIL 2DROP ;
\ TEMPO (microsecondi) DELAYMS 
: DELAYMS SYSTCLO @ BEGIN 2DUP SYSTCLO @ TIMEPASSED <= UNTIL 2DROP ;

\ WORD PER OTTENER UN NUMERO RANDOM
\ MAXVAL RAND
: RAND SYSTCLO @ SWAP MOD ;

\ WORD PER CREARE LA MASCHERA DI BIT PER ANALIZZARE/SETTARE QUEL PIN PARTICOLARE
\ PIN SELPIN 
: SELPIN 1 SWAP LSHIFT ;



