HEX

\ FILE DOVE VENGONO DEFINITE LE WORD DI GESTIONE DEL DISPLAY

\ X Y COLOR COLORPOINT  ( Word che colora di COLOR il punto X Y)
: COLORPOINT FRAMEBUFFER 2SWAP 1000 * SWAP 4 * + + 2DUP ! ;

\ X Y VALFB (RESTITUISCE IL VALORE DEL FRAMEBUFFER IN QUEL PUNTO X Y)
: VALFB 0 FRAMEBUFFER 2SWAP 1000 * SWAP 4 * + + SWAP DROP ;

\ WORD CHE TRACCIA UN SEGMENTO ORIZZONTALE TRA DUE PUNTI 
\ X1 X2 Y COLOR ORIZ
VARIABLE DISTX
: ORIZ 2SWAP SWAP 2DUP - DISTX ! 2SWAP COLORPOINT BEGIN 4 + 2DUP ! DISTX @ 1 - DUP DISTX ! 0 = UNTIL 2DROP DROP ;

\ WORD CHE TRACCIA UN SEGMENTO VERTICALE TRA DUE PUNTI 
\ Y1 Y2 X COLOR VERT
VARIABLE DISTY
: VERT 2SWAP SWAP 2DUP - DISTY ! 2SWAP ROT SWAP COLORPOINT BEGIN 1000 + 2DUP ! DISTY @ 1 - DUP DISTY ! 0 = UNTIL 2DROP DROP ;

\ WORD CHE DATI DUE PUNTI (X,Y) DISEGNA IL SEGMENTO CHE LI CONGIUNGE
\ X1 Y1 X2 Y2 COLOR SEGMENT
\ x = k, y = k, y = x e y = -x
VARIABLE X1
VARIABLE Y1
VARIABLE X2
VARIABLE Y2
VARIABLE COLOR
: SEGMENT COLOR ! Y2 ! X2 ! Y1 ! X1 ! 
	Y1 @ Y2 @ - 0 = IF  X1 @ X2 @ Y1 @ COLOR @ ORIZ  ELSE 
	X1 @ X2 @ - 0 = IF  Y1 @ Y2 @ X1 @ COLOR @ VERT  ELSE
	THEN THEN ;

\ ARRAY ( NON FUNZIONA ARRAY ) DEL PUNTATORE CORRENTE POINTER 1 CELLS + @ PER LEGGERE L'N-ESIMO VALORE
\ IL PUNTATORE PARTE DAL CENTRO DEL TASTIERINO DELLO SFONDO (quadrato 100x100)
VARIABLE POINTERX
VARIABLE POINTERY
100 POINTERX !
100 POINTERY !

VARIABLE OFFSET
VARIABLE CROSSX
VARIABLE CROSSY
VARIABLE COLORCROSS
9 OFFSET !

\ WORD CHE DISEGNA UNA CROCE NEL PUNTO X Y DI OFFSET "OFFSET" 
\ X Y OFFSET COLOR DRAWCROSS
: DRAWCROSS COLORCROSS ! OFFSET ! CROSSY ! CROSSX ! CROSSX @ CROSSY @ OFFSET @ - CROSSX @ CROSSY @ OFFSET @ + COLORCROSS @ SEGMENT CROSSX @ OFFSET @ - CROSSY @ CROSSX @ OFFSET @ + CROSSY @ COLORCROSS @ SEGMENT ;

VARIABLE SQUAREX
VARIABLE SQUAREY
VARIABLE COLORSQUARE

\ WORD CHE DISEGNA UN QUADRATO NEL PUNTO X Y DI OFFSET "OFFSET"
\ X Y OFFSET COLOR DRAWSQUARE
: DRAWSQUARE COLORSQUARE ! OFFSET ! SQUAREY ! SQUAREX ! SQUAREX @ OFFSET @ - SQUAREY @ OFFSET @ - SQUAREX @ OFFSET @ + SQUAREY @ OFFSET @ - COLORSQUARE @ SEGMENT SQUAREX @ OFFSET @ - SQUAREY @ OFFSET @ - SQUAREX @ OFFSET @ - SQUAREY @ OFFSET @ + COLORSQUARE @ SEGMENT SQUAREX @ OFFSET @ + SQUAREY @ OFFSET @ - SQUAREX @ OFFSET @ + SQUAREY @ OFFSET @ + COLORSQUARE @ SEGMENT SQUAREX @ OFFSET @ - SQUAREY @ OFFSET @ + SQUAREX @ OFFSET @ + SQUAREY @ OFFSET @ + COLORSQUARE @ SEGMENT ;

\ WORD CHE DISEGNA IL PUNTATORE
\ DRAWPOINTER in (POINTERX, POINTERY)
: DRAWPOINTER POINTERX @ POINTERY @ 7 BLACK DRAWSQUARE POINTERX @ POINTERY @ 11 GREEN DRAWCROSS ;

\ WORD PER DISEGNARE I BLOCCHI VERDI PER IL FEEDBACK A SCHERMO
\ X Y COLOR DRAWCHECK
VARIABLE CHECKBOXX 
VARIABLE CHECKBOXY

\ CANCELLA IL VECCHIO PUNTATORE PER FARE IL MOVIMENTO
: CLEAR POINTERX @ POINTERY @ 7 LIGHTGREY DRAWSQUARE POINTERX @ POINTERY @ 11 LIGHTGREY DRAWCROSS ;




























