HEX

\ FILE CHE GESTISCE L'OUTPUT, QUINDI LED E MOSTRARE A SCHERMO

\ WORD CHE DATO IL NUMERO DEL PIN IN HEX LO CONFIGURA IN OUTPUT 
\ CALCOLA IL GPFSEL REGISTER APPROPRIATO
\ OGNI REGISTRO GESTISCE 10 PIN, QUINDI IL QUOTO PER 10 MI DIRA' L'OFFSET DEL REGISTRO CORRETTO E IL RESTO SARA'
\ IL VALORE MOD 10 CIOE' BASTA MOLTIPLICARE PER 3 E SARA' IL NUMERO DEL BIT CHE SARA' IL MENO SIGNIFICATIVO DELLA TERNA PER LA CONFIG
\ PIN OUTPIN 
: OUTPIN A /MOD 4 * GPFSEL0 + SWAP 3 * SELPIN SWAP DUP ROT ROT @ OR SWAP ! ; 

\ WORD PER CHE ABILITA I PIN SCELTI PER L'OUTPUT DEL LED E LI CONFIGURA IN OUTPUT 
: ENABLEPINOUTPUT REDLED OUTPIN GREENLED OUTPIN ;

\ COLOR LED ON-OFF
: LED GPSET0 GPCLR0 ;    
: ON DROP ! ; 
: OFF NIP ! ; 

\ WORD DEI COLORI DEL LED
: ROSSO REDLED SELPIN ;					
: VERDE GREENLED SELPIN ;

\ WORD PER DUPLICARE LA TERNA SULLO STACK
: 3DUP DUP 2OVER ROT ;  

\ WORD PER FARE SEMPLICEMENTE ON-OFF 1 SECONDO (NO DELAY DOPO OFF)
: BLINK 3DUP ON 1 DELAY OFF ;

\ N COLORE LED BLINKS 20000 MICROSECONDI
VARIABLE TIMES
: BLINKS BASEONTOP TIMES ! BEGIN 3DUP 3DUP ON 20000 DELAYMS OFF 20000 DELAYMS TIMES @  1 - DUP TIMES ! 0 = UNTIL DROP 2DROP ; 

\ WORD CHE DATA UNA CIFRA LA STAMPA NEL PUNTO X Y
\ X Y COLOR CIFRA DIMENSION PRINTCIFRA
: PRINTCIFRA SWAP 30 + FINDCHAR SWAP DRAWCHAR ;

\ WORD CHE DATO UN NUMERO RESTITUISCE LE SUE CIFRE
VARIABLE COUNTERCIFRE
: NUMTOCIFRE 0 COUNTERCIFRE ! BEGIN 10 /MOD DUP COUNTERCIFRE @ 1 + COUNTERCIFRE ! 0 = UNTIL DROP ;

\ WORD CHE STAMPA UN NUMERO QUALSIASI NEL PUNTO X Y - SERVONO DUE CONTATORI, UNO PER IL PAR STACK E L'ALTRO PER STAMPARE LE CIFRE
\ X Y COLOR NUMERO DIMENSION PRINTNUM
VARIABLE CIFRAX
VARIABLE CIFRAY
VARIABLE CIFRACOLOR
VARIABLE CIFRADIM
: PRINTNUM  CIFRADIM ! SWAP CIFRACOLOR ! SWAP CIFRAY ! SWAP CIFRAX ! NUMTOCIFRE
			BEGIN CIFRAX @ SWAP CIFRAY @ SWAP CIFRACOLOR @ SWAP CIFRADIM @ PRINTCIFRA CIFRAX @ CIFRADIM @ 8 * + CIFRAX ! COUNTERCIFRE @ 1 - DUP COUNTERCIFRE ! 0 = UNTIL ;

\ WORD CHE DATA UNA STRINGA DI CODICI ASCII RESTITUISCE NELLO STACK I CODICI DEI SINGOLI CARATTERI 
VARIABLE CTRLETTER
\ : STRLEN 0 CTRLETTER ! BEGIN DROP CTRLETTER @ 1 + CTRLETTER ! DUP 0 = UNTIL ;

\ WORD CHE DATA UNA STRINGA COME SEQUENZA DI CODICI ASCII E LA SUA LUNGHEZZA LA STAMPA DA (X,Y) 
\ ASCII1 ASCII2 ASCII3... STRLEN X Y COLOR DIMENSION PRINTF
VARIABLE PRINTX
VARIABLE PRINTY
VARIABLE PRINTCOLOR
VARIABLE PRINTDIM
VARIABLE STRLEN
VARIABLE CTR
: PRINTF    PRINTDIM ! PRINTCOLOR ! PRINTY ! PRINTX ! DUP STRLEN ! CTR ! BEGIN >R CTR @ 1 - DUP CTR ! 0 = UNTIL 
			BEGIN PRINTX @ PRINTY @ PRINTCOLOR @ R> FINDCHAR PRINTDIM @ DRAWCHAR PRINTX @ PRINTDIM @ 8 * + PRINTX ! STRLEN @ 1 - DUP STRLEN ! 0 = UNTIL ;

\ WORD PER STAMPARE "APERTA!" IN 550 x 600, 226 258
: OPENMESSAGE 41 50 45 52 54 41 21 7 226 258 LIGHTGREY 4 PRINTF ; 
 






 


