HEX 

\ FILE PER LANCIARE IL GIOCO

\ WORD DA UTILIZZARE SOLO LA PRIMA VOLTA 
: START ENABLEPININPUT ENABLEPINOUTPUT BACKGROUND 1 DELAY BUILDSEQUENCE ;

\ ROUTINE DI GIOCO
: STARTGAME DRAWPOINTER BEGIN 7500 DELAYMS UPMOVE 7500 DELAYMS DOWNMOVE 7500 DELAYMS LEFTMOVE 7500 DELAYMS RIGHTMOVE 7500 DELAYMS MIDCLICK 7500 DELAYMS ENDGAME @ 0 = UNTIL UPDATESCORE 2BC FA LIGHTGREY ATTEMPTS @ TODECIMAL 4 PRINTNUM  ;

\ FUNZIONE DI RESET
: RESET RESETEVENTS BACKGROUND 2BC 1A4 LIGHTGREY BESTATTEMPTS @ TODECIMAL 4 PRINTNUM BUILDSEQUENCE 100 POINTERX ! 100 POINTERY ! 1 ENDGAME ! 1 NUMCELLATES ! 80 CHECKY ! 0 ATTEMPTS ! ;
 

\ PER LANCIARE IL GIOCO LA PRIMA VOLTA: START STARTGAME, POI RESET STARTGAME






